### ISSUE TITLE
SystemStackError error on Ubuntu Options 

### ISSUE THREAD

**Issue by veebs** [bpm/bpm#33]
I've installed ruby 1.9.2 P290 and get this error when running bpm. 

vibul@ubuntu:~/Downloads/ruby-1.9.2-p290$ bpm init my_app 
/usr/lib/ruby/1.9.2-p290/yaml.rb:30: warning: already initialized constant ENGINE 
/usr/lib/ruby/1.9.2-p290/yaml.rb:36: warning: already initialized constant ENGINE 
/usr/lib/ruby/1.9.2-p290/yaml.rb:40: warning: already initialized constant ENGINE 
/usr/lib/ruby/1.9.2-p290/yaml.rb:30: warning: already initialized constant ENGINE 
/usr/lib/ruby/1.9.2-p290/yaml.rb:36: warning: already initialized constant ENGINE 
/usr/lib/ruby/1.9.2-p290/yaml.rb:40: warning: already initialized constant ENGINE 
/usr/lib/ruby/1.9.2-p290/date.rb:236: warning: already initialized constant MONTHNAMES 
/usr/lib/ruby/1.9.2-p290/date.rb:242: warning: already initialized constant DAYNAMES 
/usr/lib/ruby/1.9.2-p290/date.rb:245: warning: already initialized constant ABBR_MONTHNAMES 
/usr/lib/ruby/1.9.2-p290/date.rb:249: warning: already initialized constant ABBR_DAYNAMES 
/usr/bin/bpm:19: stack level too deep (SystemStackError) 

Peter suggested I raise an issue here in the hope and someone with ubuntu and ruby experience can lend a hand

Thanks
Veebs

**Comment by wagenet** [comment]
How did you install Ruby?

**Comment by veebs** [comment]
Hi Peter,

I downloaded the source code and compiled it.

http://www.veebsbraindump.com/2011/03/installing-ruby-1-9-2-on-ubuntu-10-04-with-update-alternatives/

I've had success with this install process for sc-server and other ruby gems.

I've tried bpm with ruby 1.9.2 p180 and p290.

Thanks
Veebs

**Comment by gutenye** [comment]
fix it

```
$ gem install psych
```

actually it's a libgems's bug'

```
$ ruby -e "require 'libgems'"  # without psych installed.
/usr/lib/ruby/1.9.1/yaml.rb:30: warning: already initialized constant ENGINE
/usr/lib/ruby/1.9.1/yaml.rb:36: warning: already initialized constant ENGINE
/usr/lib/ruby/1.9.1/yaml.rb:40: warning: already initialized constant ENGINE
/usr/lib/ruby/1.9.1/yaml.rb:30: warning: already initialized constant ENGINE
/usr/lib/ruby/1.9.1/yaml.rb:36: warning: already initialized constant ENGINE
/usr/lib/ruby/1.9.1/yaml.rb:40: warning: already initialized constant ENGINE
/usr/lib/ruby/1.9.1/date/format.rb:8: warning: already initialized constant MONTHS
/usr/lib/ruby/1.9.1/date/format.rb:14: warning: already initialized constant DAYS
/usr/lib/ruby/1.9.1/date/format.rb:19: warning: already initialized constant ABBR_MONTHS
/usr/lib/ruby/1.9.1/date/format.rb:25: warning: already initialized constant ABBR_DAYS
<internal:lib/rubygems/custom_require>:33: stack level too deep (SystemStackError)
ruby -e 'require "libgems"'  10.13s user 2.01s system 98% cpu 12.279 total
```

backtrack:

```
        ......
    from /usr/lib/ruby/gems/1.9.1/gems/libgems-0.1.2/lib/libgems.rb:425:in `load_configuration'
    from /usr/lib/ruby/gems/1.9.1/gems/libgems-0.1.2/lib/libgems.rb:413:in `configuration'
    from /usr/lib/ruby/gems/1.9.1/gems/libgems-0.1.2/lib/libgems.rb:716:in `path'
    from /usr/lib/ruby/gems/1.9.1/gems/libgems-0.1.2/lib/libgems/source_index.rb:68:in `installed_spec_directories'
    from /usr/lib/ruby/gems/1.9.1/gems/libgems-0.1.2/lib/libgems/source_index.rb:58:in `from_installed_gems'
    from /usr/lib/ruby/gems/1.9.1/gems/libgems-0.1.2/lib/libgems.rb:971:in `source_index'
    from /usr/lib/ruby/gems/1.9.1/gems/libgems-0.1.2/lib/libgems/gem_path_searcher.rb:81:in `init_gemspecs'
    from /usr/lib/ruby/gems/1.9.1/gems/libgems-0.1.2/lib/libgems/gem_path_searcher.rb:13:in `initialize'
    from /usr/lib/ruby/gems/1.9.1/gems/libgems-0.1.2/lib/libgems.rb:930:in `new'
    from /usr/lib/ruby/gems/1.9.1/gems/libgems-0.1.2/lib/libgems.rb:930:in `searcher'
    from /usr/lib/ruby/gems/1.9.1/gems/libgems-0.1.2/lib/libgems.rb:1263:in `try_activate'
    from /usr/lib/ruby/gems/1.9.1/gems/libgems-0.1.2/lib/libgems/custom_require.rb:45:in `rescue in require'
    from /usr/lib/ruby/gems/1.9.1/gems/libgems-0.1.2/lib/libgems/custom_require.rb:40:in `require'
    from /usr/lib/ruby/gems/1.9.1/gems/libgems-0.1.2/lib/libgems.rb:668:in `load_yaml'
    from /usr/lib/ruby/gems/1.9.1/gems/libgems-0.1.2/lib/libgems/config_file.rb:218:in `load_file'
    from /usr/lib/ruby/gems/1.9.1/gems/libgems-0.1.2/lib/libgems/config_file.rb:167:in `initialize'
    from /usr/lib/ruby/gems/1.9.1/gems/libgems-0.1.2/lib/libgems.rb:425:in `new'
    from /usr/lib/ruby/gems/1.9.1/gems/libgems-0.1.2/lib/libgems.rb:425:in `load_configuration'
    from /usr/lib/ruby/gems/1.9.1/gems/libgems-0.1.2/lib/libgems.rb:413:in `configuration'
    from /usr/lib/ruby/gems/1.9.1/gems/libgems-0.1.2/lib/libgems.rb:716:in `path'
    from /usr/lib/ruby/gems/1.9.1/gems/libgems-0.1.2/lib/libgems/source_index.rb:68:in `installed_spec_directories'
    from /usr/lib/ruby/gems/1.9.1/gems/libgems-0.1.2/lib/libgems/source_index.rb:58:in `from_installed_gems'
    from /usr/lib/ruby/gems/1.9.1/gems/libgems-0.1.2/lib/libgems.rb:971:in `source_index'
    from /usr/lib/ruby/gems/1.9.1/gems/libgems-0.1.2/lib/libgems/gem_path_searcher.rb:81:in `init_gemspecs'
    from /usr/lib/ruby/gems/1.9.1/gems/libgems-0.1.2/lib/libgems/gem_path_searcher.rb:13:in `initialize'
    from /usr/lib/ruby/gems/1.9.1/gems/libgems-0.1.2/lib/libgems.rb:930:in `new'
    from /usr/lib/ruby/gems/1.9.1/gems/libgems-0.1.2/lib/libgems.rb:930:in `searcher'
    from /usr/lib/ruby/gems/1.9.1/gems/libgems-0.1.2/lib/libgems.rb:1263:in `try_activate'
    from /usr/lib/ruby/gems/1.9.1/gems/libgems-0.1.2/lib/libgems/custom_require.rb:45:in `rescue in require'
    from /usr/lib/ruby/gems/1.9.1/gems/libgems-0.1.2/lib/libgems/custom_require.rb:40:in `require'
    from /usr/lib/ruby/gems/1.9.1/gems/libgems-0.1.2/lib/libgems.rb:668:in `load_yaml'
    from /usr/lib/ruby/gems/1.9.1/gems/libgems-0.1.2/lib/libgems/config_file.rb:218:in `load_file'
    from /usr/lib/ruby/gems/1.9.1/gems/libgems-0.1.2/lib/libgems/config_file.rb:167:in `initialize'
    from /usr/lib/ruby/gems/1.9.1/gems/libgems-0.1.2/lib/libgems.rb:425:in `new'
    from /usr/lib/ruby/gems/1.9.1/gems/libgems-0.1.2/lib/libgems.rb:425:in `load_configuration'
    from /usr/lib/ruby/gems/1.9.1/gems/libgems-0.1.2/lib/libgems.rb:1274:in `<top (required)>'
    from <internal:lib/rubygems/custom_require>:33:in `require'
    from <internal:lib/rubygems/custom_require>:33:in `rescue in require'
    from <internal:lib/rubygems/custom_require>:29:in `require'
    from -e:1:in `<main>'
```

it  loads  `from /usr/lib/ruby/gems/1.9.1/gems/libgems-0.1.2/lib/libgems.rb:425:in 'load_configuration'`, again and again.

**Comment by wagenet** [comment]
Can you file an issue on libgems here: https://github.com/strobecorp/libgems/issues.
Thanks!

**Comment by gutenye** [comment]
yes, new issue is at https://github.com/strobecorp/libgems/issues/2

**Comment by veebs** [comment]
Thanks so much Guten for tracking this down.
