### ISSUE TITLE
BPM Beta 12: Error fetching SproutCore Touch

### ISSUE THREAD

**Issue by LuisSala** [bpm/bpm#7]
I'm fetching sproutcore-touch via BPM and get this error:

luis@Q:demogram2 $ bpm fetch sproutcore-touch --pre
/Users/luis/.rvm/gems/ruby-1.9.2-p290/gems/libgems-0.0.5/lib/libgems/specification.rb:289:in `load': uninitialized constant Psych::Syck (NameError)
    from /Users/luis/.rvm/gems/ruby-1.9.2-p290/gems/libgems-0.0.5/lib/libgems/specification.rb:289:in`_load'
    from /Users/luis/.rvm/gems/ruby-1.9.2-p290/gems/libgems-0.0.5/lib/libgems/spec_fetcher.rb:133:in `load'
    from /Users/luis/.rvm/gems/ruby-1.9.2-p290/gems/libgems-0.0.5/lib/libgems/spec_fetcher.rb:133:in`fetch_spec'
    from /Users/luis/.rvm/gems/ruby-1.9.2-p290/gems/libgems-0.0.5/lib/libgems/spec_fetcher.rb:87:in `block in fetch_with_errors'
    from /Users/luis/.rvm/gems/ruby-1.9.2-p290/gems/libgems-0.0.5/lib/libgems/spec_fetcher.rb:86:in`map'
    from /Users/luis/.rvm/gems/ruby-1.9.2-p290/gems/libgems-0.0.5/lib/libgems/spec_fetcher.rb:86:in `fetch_with_errors'
    from /Users/luis/.rvm/gems/ruby-1.9.2-p290/gems/bpm-1.0.0.beta.12/lib/bpm/libgems_ext/dependency_installer.rb:129:in`find_gems_with_sources'
    from /Users/luis/.rvm/gems/ruby-1.9.2-p290/gems/bpm-1.0.0.beta.12/lib/bpm/libgems_ext/dependency_installer.rb:36:in `find_spec_by_name_and_version'
    from /Users/luis/.rvm/gems/ruby-1.9.2-p290/gems/bpm-1.0.0.beta.12/lib/bpm/libgems_ext/dependency_installer.rb:56:in`block in install'
    from /Users/luis/.rvm/gems/ruby-1.9.2-p290/gems/libgems-0.0.5/lib/libgems.rb:194:in `with_rubygems_compat'
    from /Users/luis/.rvm/gems/ruby-1.9.2-p290/gems/bpm-1.0.0.beta.12/lib/bpm/libgems_ext/dependency_installer.rb:54:in`install'
    from /Users/luis/.rvm/gems/ruby-1.9.2-p290/gems/bpm-1.0.0.beta.12/lib/bpm/remote.rb:83:in `block in install'
    from /Users/luis/.rvm/gems/ruby-1.9.2-p290/gems/bpm-1.0.0.beta.12/lib/bpm/libgems_ext/libgems.rb:43:in`with_silence'
    from /Users/luis/.rvm/gems/ruby-1.9.2-p290/gems/bpm-1.0.0.beta.12/lib/bpm/remote.rb:81:in `install'
    from /Users/luis/.rvm/gems/ruby-1.9.2-p290/gems/bpm-1.0.0.beta.12/lib/bpm/cli/base.rb:41:in`block in fetch'
    from /Users/luis/.rvm/gems/ruby-1.9.2-p290/gems/bpm-1.0.0.beta.12/lib/bpm/cli/base.rb:40:in `each'
    from /Users/luis/.rvm/gems/ruby-1.9.2-p290/gems/bpm-1.0.0.beta.12/lib/bpm/cli/base.rb:40:in`fetch'
    from /Users/luis/.rvm/gems/ruby-1.9.2-p290/gems/thor-0.14.6/lib/thor/task.rb:22:in `run'
    from /Users/luis/.rvm/gems/ruby-1.9.2-p290/gems/thor-0.14.6/lib/thor/invocation.rb:118:in`invoke_task'
    from /Users/luis/.rvm/gems/ruby-1.9.2-p290/gems/thor-0.14.6/lib/thor.rb:263:in `dispatch'
    from /Users/luis/.rvm/gems/ruby-1.9.2-p290/gems/thor-0.14.6/lib/thor/base.rb:389:in`start'
    from /Users/luis/.rvm/gems/ruby-1.9.2-p290/gems/bpm-1.0.0.beta.12/bin/bpm:7:in `<top (required)>'
    from /Users/luis/.rvm/gems/ruby-1.9.2-p290/bin/bpm:19:in`load'
    from /Users/luis/.rvm/gems/ruby-1.9.2-p290/bin/bpm:19:in `<main>'

**Comment by LuisSala** [comment]
Disregard, needed to re-fetch Spade.
