### ISSUE TITLE
bpm list -r error

### ISSUE THREAD

**Issue by gutenye** [bpm/bpm#77]
$ bpm list -r

```
/usr/lib/ruby/gems/1.9.1/gems/libgems-0.1.3/lib/libgems/remote_fetcher.rb:180:in `rescue in fetch_path': Errno::ECONNREFUSED: Connection refused - connect(2) (https://getbpm.org/latest_specs.4.8.gz) (LibGems::RemoteFetcher::FetchError)
    from /usr/lib/ruby/gems/1.9.1/gems/libgems-0.1.3/lib/libgems/remote_fetcher.rb:172:in `fetch_path'
    from /usr/lib/ruby/gems/1.9.1/gems/libgems-0.1.3/lib/libgems/spec_fetcher.rb:278:in `load_specs'
    from /usr/lib/ruby/gems/1.9.1/gems/libgems-0.1.3/lib/libgems/spec_fetcher.rb:251:in `block in list'
    from /usr/lib/ruby/gems/1.9.1/gems/libgems-0.1.3/lib/libgems/spec_fetcher.rb:247:in `each'
    from /usr/lib/ruby/gems/1.9.1/gems/libgems-0.1.3/lib/libgems/spec_fetcher.rb:247:in `list'
    from /usr/lib/ruby/gems/1.9.1/gems/libgems-0.1.3/lib/libgems/spec_fetcher.rb:146:in `find_matching_with_errors'
    from /usr/lib/ruby/gems/1.9.1/gems/libgems-0.1.3/lib/libgems/spec_fetcher.rb:173:in `find_matching'
    from /usr/lib/ruby/gems/1.9.1/gems/bpm-1.0.0.rc.3/lib/bpm/remote.rb:71:in `list_packages'
    from /usr/lib/ruby/gems/1.9.1/gems/bpm-1.0.0.rc.3/lib/bpm/cli/base.rb:223:in `list'
    from /usr/lib/ruby/gems/1.9.1/gems/thor-0.14.6/lib/thor/task.rb:22:in `run'
    from /usr/lib/ruby/gems/1.9.1/gems/thor-0.14.6/lib/thor/invocation.rb:118:in `invoke_task'
    from /usr/lib/ruby/gems/1.9.1/gems/thor-0.14.6/lib/thor.rb:263:in `dispatch'
    from /usr/lib/ruby/gems/1.9.1/gems/thor-0.14.6/lib/thor/base.rb:389:in `start'
    from /usr/lib/ruby/gems/1.9.1/gems/bpm-1.0.0.rc.3/lib/bpm/cli/base.rb:25:in `start'
    from /usr/lib/ruby/gems/1.9.1/gems/bpm-1.0.0.rc.3/bin/bpm:8:in `<top (required)>'
    from /usr/bin/bpm:19:in `load'
    from /usr/bin/bpm:19:in `<main>'
```

I can't connect to https://getbpm.org/latest_specs.4.8.gz, but can connect to https://www.getbpm.org/latest_specs.4.8.gz

**Comment by gutenye** [comment]
there is no this error anymore. sorry about this.

**Comment by gutenye** [comment]
I fond the problem.

https://getbpm.org  # not work
https://www.getbpm.org # works
http://getbpm.org redirect to https://www.getbpm.org # works

plz fix https://getbpm.org domain.

**Comment by wagenet** [comment]
Update to version 1.0.0.
