### ISSUE TITLE
getting error after adding spin.js

### ISSUE THREAD

**Issue by rsaccon** [bpm/bpm#89]
I am on mac OS X 10.7.2 and RVM 1.9.2

Unfortunately, a fatal error has occurred. Please report this error to the BPM issue tracker at https://github.com/bpm/bpm/issues so that we can fix it. Thanks!
/Users/robertosaccon/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/fileutils.rb:243:in `mkdir': File exists - /Users/robertosaccon/Documents/workspace/unpaperfy/war/unpaperfy/.bpm/preview/spin.js (Errno::EEXIST)
    from /Users/robertosaccon/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/fileutils.rb:243:in`fu_mkdir'
    from /Users/robertosaccon/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/fileutils.rb:217:in `block (2 levels) in mkdir_p'
    from /Users/robertosaccon/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/fileutils.rb:215:in`reverse_each'
    from /Users/robertosaccon/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/fileutils.rb:215:in `block in mkdir_p'
    from /Users/robertosaccon/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/fileutils.rb:201:in`each'
    from /Users/robertosaccon/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/fileutils.rb:201:in `mkdir_p'
    from /Users/robertosaccon/.rvm/gems/ruby-1.9.2-p290/gems/bpm-1.0.0/lib/bpm/project.rb:195:in`block in rebuild_preview'
    from /Users/robertosaccon/.rvm/gems/ruby-1.9.2-p290/gems/bpm-1.0.0/lib/bpm/project.rb:193:in `each'
    from /Users/robertosaccon/.rvm/gems/ruby-1.9.2-p290/gems/bpm-1.0.0/lib/bpm/project.rb:193:in`rebuild_preview'
    from /Users/robertosaccon/.rvm/gems/ruby-1.9.2-p290/gems/bpm-1.0.0/lib/bpm/project.rb:177:in `verify_and_repair'
    from /Users/robertosaccon/.rvm/gems/ruby-1.9.2-p290/gems/bpm-1.0.0/lib/bpm/cli/base.rb:217:in`preview'
    from /Users/robertosaccon/.rvm/gems/ruby-1.9.2-p290/gems/thor-0.14.6/lib/thor/task.rb:22:in `run'
    from /Users/robertosaccon/.rvm/gems/ruby-1.9.2-p290/gems/thor-0.14.6/lib/thor/invocation.rb:118:in`invoke_task'
    from /Users/robertosaccon/.rvm/gems/ruby-1.9.2-p290/gems/thor-0.14.6/lib/thor.rb:263:in `dispatch'
    from /Users/robertosaccon/.rvm/gems/ruby-1.9.2-p290/gems/thor-0.14.6/lib/thor/base.rb:389:in`start'
    from /Users/robertosaccon/.rvm/gems/ruby-1.9.2-p290/gems/bpm-1.0.0/lib/bpm/cli/base.rb:59:in `start'
    from /Users/robertosaccon/.rvm/gems/ruby-1.9.2-p290/gems/bpm-1.0.0/bin/bpm:8:in`<top (required)>'
    from /Users/robertosaccon/.rvm/gems/ruby-1.9.2-p290/bin/bpm:19:in `load'
    from /Users/robertosaccon/.rvm/gems/ruby-1.9.2-p290/bin/bpm:19:in`<main>'

**Comment by cdchapman** [comment]
It looks like the period `.` in _spin.js_ is [confusing bpm](https://github.com/bpm/bpm/blob/master/lib/bpm/project.rb#L168). A quick workaround would be to rename the package as _spin-js_ or simply _spin_. Regarding a better fix, is there any reason that bpm should not be able to handle packages with periods `.` in the name?

**Comment by cdchapman** [comment]
I yanked spin.js and pushed [spin](https://www.getbpm.org/gems/spin), following the precedent of [underscore](https://www.getbpm.org/gems/underscore). This should work for you, at least for now.
