### ISSUE TITLE
No such file or directory -  C:/Program Files  (x86)/BPM/local/bpm/bundle/ruby/1.9.1/gems/execjs-1.2.4/lib/execjs/support/whic h.bat nodejs

### ISSUE THREAD

**Issue by lhwong** [bpm/bpm#93]
I got the following error when running "bpm init hello_world"

My system details:
bpm version 1.0.0
OS: Windows 7

C:\Users\lhwong\Desktop\Zilant Health Server\hello_world>bpm init hello_world
C:/Program Files (x86)/BPM/local/bpm/lib/bpm/libgems_ext/config_file.rb:9: warni
ng: already initialized constant CSIDL_COMMON_APPDATA
C:/Program Files (x86)/BPM/local/bpm/lib/bpm/libgems_ext/config_file.rb:12: warn
ing: already initialized constant SHGetFolderPath
      create  lib
      create  LICENSE
      create  README.md
      create  index.html
      create  lib/main.js
      create  css/main.css
      create  hello_world.json
Building static assets...
~ Using fetched package 'uglify-js' (1.0.7)
~ Using fetched package 'spade' (1.0.2)
Unfortunately, a fatal error has occurred. Please report this error to the BPM i
ssue tracker at https://github.com/bpm/bpm/issues so that we can fix it. Thanks!

C:/Program Files (x86)/BPM/local/bpm/bundle/ruby/1.9.1/gems/execjs-1.2.4/lib/exe
cjs/external_runtime.rb:146:in ``': No such file or directory - C:/Program Files
 (x86)/BPM/local/bpm/bundle/ruby/1.9.1/gems/execjs-1.2.4/lib/execjs/support/whic
h.bat nodejs (Errno::ENOENT)
  (in C:/Users/lhwong/.bpm/gems/uglify-js-1.0.7/lib/parse-js.js)
        from C:/Program Files (x86)/BPM/local/bpm/bundle/ruby/1.9.1/gems/execjs-
1.2.4/lib/execjs/external_runtime.rb:146:in`block in which'
        from C:/Program Files (x86)/BPM/local/bpm/bundle/ruby/1.9.1/gems/execjs-
1.2.4/lib/execjs/external_runtime.rb:143:in `each'
        from C:/Program Files (x86)/BPM/local/bpm/bundle/ruby/1.9.1/gems/execjs-
1.2.4/lib/execjs/external_runtime.rb:143:in`which'
        from C:/Program Files (x86)/BPM/local/bpm/bundle/ruby/1.9.1/gems/execjs-
1.2.4/lib/execjs/external_runtime.rb:132:in `locate_binary'
        from C:/Program Files (x86)/BPM/local/bpm/bundle/ruby/1.9.1/gems/execjs-
1.2.4/lib/execjs/external_runtime.rb:94:in`initialize'
        from C:/Program Files (x86)/BPM/local/bpm/bundle/ruby/1.9.1/gems/execjs-
1.2.4/lib/execjs/runtimes.rb:18:in `new'
        from C:/Program Files (x86)/BPM/local/bpm/bundle/ruby/1.9.1/gems/execjs-
1.2.4/lib/execjs/runtimes.rb:18:in`module:Runtimes'
        from C:/Program Files (x86)/BPM/local/bpm/bundle/ruby/1.9.1/gems/execjs-
1.2.4/lib/execjs/runtimes.rb:9:in `<module:ExecJS>'
        from C:/Program Files (x86)/BPM/local/bpm/bundle/ruby/1.9.1/gems/execjs-
1.2.4/lib/execjs/runtimes.rb:8:in`<top (required)>'
        from C:/Program Files (x86)/BPM/ruby/lib/ruby/site_ruby/1.9.1/rubygems/c
ustom_require.rb:36:in `require'
        from C:/Program Files (x86)/BPM/ruby/lib/ruby/site_ruby/1.9.1/rubygems/c
ustom_require.rb:36:in`require'
        from C:/Program Files (x86)/BPM/local/bpm/bundle/ruby/1.9.1/gems/libgems
-0.1.3/lib/libgems/custom_require.rb:42:in `require'
        from C:/Program Files (x86)/BPM/local/bpm/bundle/ruby/1.9.1/gems/execjs-
1.2.4/lib/execjs.rb:2:in`<top (required)>'
        from C:/Program Files (x86)/BPM/ruby/lib/ruby/site_ruby/1.9.1/rubygems/c
ustom_require.rb:36:in `require'
        from C:/Program Files (x86)/BPM/ruby/lib/ruby/site_ruby/1.9.1/rubygems/c
ustom_require.rb:36:in`require'
        from C:/Program Files (x86)/BPM/local/bpm/bundle/ruby/1.9.1/gems/libgems
-0.1.3/lib/libgems/custom_require.rb:42:in `require'
        from C:/Program Files (x86)/BPM/local/bpm/lib/bpm/execjs_ext.rb:1:in`<t
op (required)>'
        from C:/Program Files (x86)/BPM/ruby/lib/ruby/site_ruby/1.9.1/rubygems/c
ustom_require.rb:36:in `require'
        from C:/Program Files (x86)/BPM/ruby/lib/ruby/site_ruby/1.9.1/rubygems/c
ustom_require.rb:36:in`require'
        from C:/Program Files (x86)/BPM/local/bpm/bundle/ruby/1.9.1/gems/libgems
-0.1.3/lib/libgems/custom_require.rb:42:in `require'
        from C:/Program Files (x86)/BPM/local/bpm/lib/bpm.rb:31:in`compile_js'
        from C:/Program Files (x86)/BPM/local/bpm/lib/bpm/pipeline/plugin_proces
sor.rb:60:in `evaluate'
        from C:/Program Files (x86)/BPM/local/bpm/bundle/ruby/1.9.1/gems/tilt-1.
3.3/lib/tilt/template.rb:76:in`render'
        from C:/Program Files (x86)/BPM/local/bpm/bundle/ruby/1.9.1/gems/sprocke
ts-2.0.0/lib/sprockets/context.rb:175:in `block in evaluate'
        from C:/Program Files (x86)/BPM/local/bpm/bundle/ruby/1.9.1/gems/sprocke
ts-2.0.0/lib/sprockets/context.rb:172:in`each'
        from C:/Program Files (x86)/BPM/local/bpm/bundle/ruby/1.9.1/gems/sprocke
ts-2.0.0/lib/sprockets/context.rb:172:in `evaluate'
        from C:/Program Files (x86)/BPM/local/bpm/bundle/ruby/1.9.1/gems/sprocke
ts-2.0.0/lib/sprockets/bundled_asset.rb:171:in`build_dependency_context_and_bod
y'
        from C:/Program Files (x86)/BPM/local/bpm/bundle/ruby/1.9.1/gems/sprocke
ts-2.0.0/lib/sprockets/bundled_asset.rb:135:in `dependency_context'
        from C:/Program Files (x86)/BPM/local/bpm/bundle/ruby/1.9.1/gems/sprocke
ts-2.0.0/lib/sprockets/bundled_asset.rb:194:in`build_dependencies_paths_and_ass
ets'
        from C:/Program Files (x86)/BPM/local/bpm/bundle/ruby/1.9.1/gems/sprocke
ts-2.0.0/lib/sprockets/bundled_asset.rb:81:in `to_a'
        from C:/Program Files (x86)/BPM/local/bpm/bundle/ruby/1.9.1/gems/sprocke
ts-2.0.0/lib/sprockets/bundled_asset.rb:239:in`block in build_source'
        from C:/Program Files (x86)/BPM/local/bpm/bundle/ruby/1.9.1/gems/sprocke
ts-2.0.0/lib/sprockets/caching.rb:23:in `cache_hash'
        from C:/Program Files (x86)/BPM/local/bpm/bundle/ruby/1.9.1/gems/sprocke
ts-2.0.0/lib/sprockets/bundled_asset.rb:235:in`build_source'
        from C:/Program Files (x86)/BPM/local/bpm/lib/bpm/pipeline.rb:153:in `fi
nd_asset'
        from C:/Program Files (x86)/BPM/local/bpm/bundle/ruby/1.9.1/gems/sprocke
ts-2.0.0/lib/sprockets/base.rb:110:in`[]'
        from C:/Program Files (x86)/BPM/local/bpm/bundle/ruby/1.9.1/gems/sprocke
ts-2.0.0/lib/sprockets/bundled_asset.rb:200:in `block in build_dependencies_path
s_and_assets'
        from C:/Program Files (x86)/BPM/local/bpm/bundle/ruby/1.9.1/gems/sprocke
ts-2.0.0/lib/sprockets/bundled_asset.rb:194:in`each'
        from C:/Program Files (x86)/BPM/local/bpm/bundle/ruby/1.9.1/gems/sprocke
ts-2.0.0/lib/sprockets/bundled_asset.rb:194:in `build_dependencies_paths_and_ass
ets'
        from C:/Program Files (x86)/BPM/local/bpm/bundle/ruby/1.9.1/gems/sprocke
ts-2.0.0/lib/sprockets/bundled_asset.rb:81:in`to_a'
        from C:/Program Files (x86)/BPM/local/bpm/bundle/ruby/1.9.1/gems/sprocke
ts-2.0.0/lib/sprockets/bundled_asset.rb:239:in `block in build_source'
        from C:/Program Files (x86)/BPM/local/bpm/bundle/ruby/1.9.1/gems/sprocke
ts-2.0.0/lib/sprockets/caching.rb:23:in`cache_hash'
        from C:/Program Files (x86)/BPM/local/bpm/bundle/ruby/1.9.1/gems/sprocke
ts-2.0.0/lib/sprockets/bundled_asset.rb:235:in `build_source'
        from C:/Program Files (x86)/BPM/local/bpm/lib/bpm/pipeline/generated_ass
et.rb:108:in`build_source'
        from C:/Program Files (x86)/BPM/local/bpm/bundle/ruby/1.9.1/gems/sprocke
ts-2.0.0/lib/sprockets/bundled_asset.rb:93:in `to_s'
        from C:/Program Files (x86)/BPM/local/bpm/lib/bpm/pipeline.rb:196:in`bu
ild_plugin_js'
        from C:/Program Files (x86)/BPM/local/bpm/lib/bpm/pipeline.rb:146:in `pl
ugin_js_for'
        from C:/Program Files (x86)/BPM/local/bpm/lib/bpm/pipeline/generated_ass
et.rb:73:in`minify_body'
        from C:/Program Files (x86)/BPM/local/bpm/lib/bpm/pipeline/generated_ass
et.rb:120:in `block in minify'
        from C:/Program Files (x86)/BPM/local/bpm/bundle/ruby/1.9.1/gems/sprocke
ts-2.0.0/lib/sprockets/caching.rb:23:in`cache_hash'
        from C:/Program Files (x86)/BPM/local/bpm/lib/bpm/pipeline/generated_ass
et.rb:119:in `minify'
        from C:/Program Files (x86)/BPM/local/bpm/lib/bpm/pipeline/generated_ass
et.rb:108:in`build_source'
        from C:/Program Files (x86)/BPM/local/bpm/lib/bpm/pipeline.rb:153:in `fi
nd_asset'
        from C:/Program Files (x86)/BPM/local/bpm/lib/bpm/pipeline.rb:142:in`bl
ock in buildable_assets'
        from C:/Program Files (x86)/BPM/local/bpm/lib/bpm/pipeline.rb:142:in `ma
p'
        from C:/Program Files (x86)/BPM/local/bpm/lib/bpm/pipeline.rb:142:in`bu
ildable_assets'
        from C:/Program Files (x86)/BPM/local/bpm/lib/bpm/project.rb:297:in `bui
ld'
        from C:/Program Files (x86)/BPM/local/bpm/lib/bpm/cli/base.rb:503:in`ru
n_init'
        from C:/Program Files (x86)/BPM/local/bpm/lib/bpm/cli/base.rb:400:in `bl
ock in init'
        from C:/Program Files (x86)/BPM/local/bpm/lib/bpm/cli/base.rb:382:in`ea
ch'
        from C:/Program Files (x86)/BPM/local/bpm/lib/bpm/cli/base.rb:382:in `in
it'
        from C:/Program Files (x86)/BPM/local/bpm/bundle/ruby/1.9.1/gems/thor-0.
14.6/lib/thor/task.rb:22:in`run'
        from C:/Program Files (x86)/BPM/local/bpm/bundle/ruby/1.9.1/gems/thor-0.
14.6/lib/thor/invocation.rb:118:in `invoke_task'
        from C:/Program Files (x86)/BPM/local/bpm/bundle/ruby/1.9.1/gems/thor-0.
14.6/lib/thor.rb:263:in`dispatch'
        from C:/Program Files (x86)/BPM/local/bpm/bundle/ruby/1.9.1/gems/thor-0.
14.6/lib/thor/base.rb:389:in `start'
        from C:/Program Files (x86)/BPM/local/bpm/lib/bpm/cli/base.rb:59:in`sta
rt'
        from C:/Program Files (x86)/BPM/bin/bpm:8:in `<main>'

**Comment by nareshbhatia** [comment]
I ran into the same issue trying to create hello_world:

Unfortunately, a fatal error has occurred. Please report this error to the BPM issue tracker at https://github.com/bpm/bpm/issues so that we can fix it. Thanks!
C:/apps/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/bpm-1.0.0/lib/bpm/execjs_ext.rb:33:in ``': No such file or directory - "C:/apps/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/execjs-1.2.13/lib/execjs/support/which.bat" cscript (Errno::ENOENT)
  (in C:/Users/Naresh/.bpm/gems/uglify-js-1.0.7/lib/parse-js.js)
        from C:/apps/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/bpm-1.0.0/lib/bpm/execjs_ext.rb:33:in`block in which'
        from C:/apps/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/bpm-1.0.0/lib/bpm/execjs_ext.rb:30:in `each'
        from C:/apps/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/bpm-1.0.0/lib/bpm/execjs_ext.rb:30:in`which'
        from C:/apps/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/execjs-1.2.13/lib/execjs/external_runtime.rb:155:in `locate_binary'
        from C:/apps/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/bpm-1.0.0/lib/bpm/execjs_ext.rb:15:in`initialize'
        from C:/apps/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/bpm-1.0.0/lib/bpm/execjs_ext.rb:71:in `new'
        from C:/apps/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/bpm-1.0.0/lib/bpm/execjs_ext.rb:71:in`module:Runtimes'
        from C:/apps/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/bpm-1.0.0/lib/bpm/execjs_ext.rb:69:in `<module:ExecJS>'
        from C:/apps/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/bpm-1.0.0/lib/bpm/execjs_ext.rb:6:in`<top (required)>'
        from C:/apps/ruby-1.9.3/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from C:/apps/ruby-1.9.3/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in`require'
        from C:/apps/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/libgems-0.1.3/lib/libgems/custom_require.rb:42:in `require'
        from C:/apps/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/bpm-1.0.0/lib/bpm.rb:31:in`compile_js'
        from C:/apps/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/bpm-1.0.0/lib/bpm/pipeline/plugin_processor.rb:60:in `evaluate'
        from C:/apps/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/tilt-1.3.3/lib/tilt/template.rb:76:in`render'
        from C:/apps/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/sprockets-2.0.3/lib/sprockets/context.rb:175:in `block in evaluate'
        from C:/apps/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/sprockets-2.0.3/lib/sprockets/context.rb:172:in`each'
        from C:/apps/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/sprockets-2.0.3/lib/sprockets/context.rb:172:in `evaluate'
        from C:/apps/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/sprockets-2.0.3/lib/sprockets/bundled_asset.rb:171:in`build_dependency_context_and_body'
        from C:/apps/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/sprockets-2.0.3/lib/sprockets/bundled_asset.rb:135:in `dependency_context'
        from C:/apps/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/sprockets-2.0.3/lib/sprockets/bundled_asset.rb:194:in`build_dependencies_paths_and_assets'
        from C:/apps/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/sprockets-2.0.3/lib/sprockets/bundled_asset.rb:81:in `to_a'
        from C:/apps/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/sprockets-2.0.3/lib/sprockets/bundled_asset.rb:239:in`block in build_source'
        from C:/apps/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/sprockets-2.0.3/lib/sprockets/caching.rb:27:in `cache_hash'
        from C:/apps/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/sprockets-2.0.3/lib/sprockets/bundled_asset.rb:235:in`build_source'
        from C:/apps/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/bpm-1.0.0/lib/bpm/pipeline.rb:153:in `find_asset'
        from C:/apps/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/sprockets-2.0.3/lib/sprockets/base.rb:110:in`[]'
        from C:/apps/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/sprockets-2.0.3/lib/sprockets/bundled_asset.rb:200:in `block in build_dependencies_paths_and_assets'
        from C:/apps/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/sprockets-2.0.3/lib/sprockets/bundled_asset.rb:194:in`each'
        from C:/apps/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/sprockets-2.0.3/lib/sprockets/bundled_asset.rb:194:in `build_dependencies_paths_and_assets'
        from C:/apps/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/sprockets-2.0.3/lib/sprockets/bundled_asset.rb:81:in`to_a'
        from C:/apps/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/sprockets-2.0.3/lib/sprockets/bundled_asset.rb:239:in `block in build_source'
        from C:/apps/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/sprockets-2.0.3/lib/sprockets/caching.rb:27:in`cache_hash'
        from C:/apps/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/sprockets-2.0.3/lib/sprockets/bundled_asset.rb:235:in `build_source'
        from C:/apps/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/bpm-1.0.0/lib/bpm/pipeline/generated_asset.rb:108:in`build_source'
        from C:/apps/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/sprockets-2.0.3/lib/sprockets/bundled_asset.rb:93:in `to_s'
        from C:/apps/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/bpm-1.0.0/lib/bpm/pipeline.rb:196:in`build_plugin_js'
        from C:/apps/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/bpm-1.0.0/lib/bpm/pipeline.rb:146:in `plugin_js_for'
        from C:/apps/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/bpm-1.0.0/lib/bpm/pipeline/generated_asset.rb:73:in`minify_body'
        from C:/apps/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/bpm-1.0.0/lib/bpm/pipeline/generated_asset.rb:120:in `block in minify'
        from C:/apps/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/sprockets-2.0.3/lib/sprockets/caching.rb:27:in`cache_hash'
        from C:/apps/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/bpm-1.0.0/lib/bpm/pipeline/generated_asset.rb:119:in `minify'
        from C:/apps/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/bpm-1.0.0/lib/bpm/pipeline/generated_asset.rb:108:in`build_source'
        from C:/apps/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/bpm-1.0.0/lib/bpm/pipeline.rb:153:in `find_asset'
        from C:/apps/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/bpm-1.0.0/lib/bpm/pipeline.rb:142:in`block in buildable_assets'
        from C:/apps/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/bpm-1.0.0/lib/bpm/pipeline.rb:142:in `map'
        from C:/apps/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/bpm-1.0.0/lib/bpm/pipeline.rb:142:in`buildable_assets'
        from C:/apps/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/bpm-1.0.0/lib/bpm/project.rb:297:in `build'
        from C:/apps/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/bpm-1.0.0/lib/bpm/cli/base.rb:503:in`run_init'
        from C:/apps/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/bpm-1.0.0/lib/bpm/cli/base.rb:400:in `block in init'
        from C:/apps/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/bpm-1.0.0/lib/bpm/cli/base.rb:382:in`each'
        from C:/apps/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/bpm-1.0.0/lib/bpm/cli/base.rb:382:in `init'
        from C:/apps/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/thor-0.14.6/lib/thor/task.rb:22:in`run'
        from C:/apps/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/thor-0.14.6/lib/thor/invocation.rb:118:in `invoke_task'
        from C:/apps/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/thor-0.14.6/lib/thor.rb:263:in`dispatch'
        from C:/apps/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/thor-0.14.6/lib/thor/base.rb:389:in `start'
        from C:/apps/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/bpm-1.0.0/lib/bpm/cli/base.rb:59:in`start'
        from C:/apps/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/bpm-1.0.0/bin/bpm:8:in `<top (required)>'
        from C:/apps/ruby-1.9.3/bin/bpm:19:in`load'
        from C:/apps/ruby-1.9.3/bin/bpm:19:in `<main>'

**Comment by roydaniels** [comment]
Please follow the instructions here to resolve this issue: [https://github.com/ud3323/bpm/wiki/Installing-with-Windows](https://github.com/ud3323/bpm/wiki/Installing-with-Windows)

**Comment by roydaniels** [comment]
This shouldn't be too hard to fix. I'll take a look at it this weekend and push fixes to my repo with a pull request here too.

**Comment by nareshbhatia** [comment]
Thanks Roy. This indeed got me going. Now I am stuck at the last step (Try
It Out!). Instead of showing "Congratulations! You are now running Hello
World v0.0.1", it is still showing "Hello World". Also I am seeing the
following error in Firebug:

Module core/main not found
http://localhost:4020/assets/bpm_libs.js (Line 255)

I am lost. I have 3 files under lib: core.js, main.js and template.js. I
don't see why the app is looking for core/main.

Naresh

On Mon, Feb 13, 2012 at 6:14 PM, ud3323 <
reply@reply.github.com

**Comment by nareshbhatia** [comment]
Another interesting thing is that if I run the same app from Apache, it
brings up the "Hello" alert box from part 1 and no error in Firebug. So as
if part 2 was never implemented. In other words, Apache server and the "bpm
preview" are working differently. Is bpm preview doing something that
Apache is not?

Thanks.
Naresh
