### ISSUE TITLE
running bpm preview

### ISSUE THREAD

**Issue by pierreva** [bpm/bpm#95]
/Users/pierreva/.rvm/gems/ruby-1.9.2-p180/gems/bpm-1.0.0/lib/bpm/server.rb:7:in `<module:BPM>': uninitialized constant Rack::Server (NameError)
    from /Users/pierreva/.rvm/gems/ruby-1.9.2-p180/gems/bpm-1.0.0/lib/bpm/server.rb:5:in`<top (required)>'
    from /Users/pierreva/.rvm/gems/ruby-1.9.2-p180/gems/bpm-1.0.0/lib/bpm/cli/base.rb:218:in `preview'
    from /Users/pierreva/.rvm/gems/ruby-1.9.2-p180/gems/thor-0.14.6/lib/thor/task.rb:22:in`run'
    from /Users/pierreva/.rvm/gems/ruby-1.9.2-p180/gems/thor-0.14.6/lib/thor/invocation.rb:118:in `invoke_task'
    from /Users/pierreva/.rvm/gems/ruby-1.9.2-p180/gems/thor-0.14.6/lib/thor.rb:263:in`dispatch'
    from /Users/pierreva/.rvm/gems/ruby-1.9.2-p180/gems/thor-0.14.6/lib/thor/base.rb:389:in `start'
    from /Users/pierreva/.rvm/gems/ruby-1.9.2-p180/gems/bpm-1.0.0/lib/bpm/cli/base.rb:59:in`start'
    from /Users/pierreva/.rvm/gems/ruby-1.9.2-p180/gems/bpm-1.0.0/bin/bpm:8:in `<top (required)>'
    from /Users/pierreva/.rvm/gems/ruby-1.9.2-p180/bin/bpm:19:in`load'
    from /Users/pierreva/.rvm/gems/ruby-1.9.2-p180/bin/bpm:19:in `<main>'

**Comment by wagenet** [comment]
Try `gem install rack`.

**Comment by pierreva** [comment]
with ruby-1.9.3-p194 it's OK
